# Generated by Django 5.0.1 on 2024-02-28 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_customer_order_orderitems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="main.order",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_product",
                to="main.productcategory",
            ),
        ),
    ]
